### ISSUE TITLE
SAR: Enter the Locator as Rescue Pilot when `Rescued - SAR` and no Rescue Pilot Entered

### ISSUE THREAD

**Issue by chigaze** [Thricehappy/EveScoutRescue#210]
Currently when a someone locates a system and is immediately able to complete the rescue they are not credited as a rescue pilot unless they remember to fly back into the system once after the locate. In these situations it is clear the locator is also the rescue pilot and should be credited as such.

**Comment by Klensor** [comment]
Not sure if this issue can be fixed here, possibly one for seperate code (911, Allison?)

**Comment by Thricehappy** [comment]
@adeadparrot Can you comment?

**Comment by chigaze** [comment]
One fix for this would be for an Admin to be able to edit SARs directly including adding pilots to a SAR.

**Comment by adeadparrot** [comment]
Notes for issue (from Igaze):

Scenario 1: SAR is opened, locator flies in, rescue team arrives, locator moves on. In this case the locator will not be listed among the rescue pilots.

Scenario 2: SAR is opened, locator flies in, rescue team arrives, locator helps with scouting. In this case the locator (as long as they flew back in once) will be listed among the rescue pilots.

Scenario 3: SAR is opened, locator flies in, locator rescues lost pilot. In this case if the locator does not re-enter the system then no rescue pilot will be listed. This is the most commen problem situation. Most often the pilot simply forgets although sometimes they just can’t get back in because the hole is camped or collapsed.

Scenario 4: SAR is opened while pilot is already in system, they complete the rescue. In this case no locator is listed and no rescuer is listed. Pilot does not receive a payout or credit for medals. See J001057 on September 11.
