### ISSUE TITLE
WH search ahead uses caches table and should use wh table

### ISSUE THREAD

**Issue by bikerunner** [Thricehappy/EveScoutRescue#41]
Background: Enter a WH name into the search field starts a type ahead search. This uses the activecaches.php script to lookup the WH information.

Problem: The script lookup the WH system name from the "caches" table. I think the WH names to search for should be from the "wh_systems" table to search for all known WH systems.

Example: Check for a system without a cache using the query "SELECT max(system) FROM `wh_systems` WHERE system not in (select system from cache)". Enter the system name characters slowly to the search field. The system name is not displayed/prefetched at the end.

The result itself generated by the search.php should lookup the "caches" table to find a cache of the entered system.

Change: Change the query in activecaches.php to lookup WH system names from correct table.

**Comment by Thricehappy** [comment]
I can see how this would end up producing cleaner code in search.php, because I wouldn't need to do all those if/else checks when we don't get a result from activecaches.php.

For now, though, this does all work correctly. You or I can get to this whenever, but not high priority -- unless this needs to be corrected for something else you are working on. If so, assign this to yourself, and go for it!

**Comment by Thricehappy** [comment]
I'm calling this an enhancement rather than a bug, because it will make the code more elegant but produce identical results for the end user -- I hope!

**Comment by Thricehappy** [comment]
Resolved in PR #54
