### ISSUE TITLE
Recheck "Do not tend within 24 hours" implementation

### ISSUE THREAD

**Issue by bikerunner** [Thricehappy/EveScoutRescue#74]
The current implementation does not allow tending a cache within 24 hours at all. This should be changed like the following:
* do not allow tending the cache within 24 hours as "healthy" after last "healthy" tending or sowing
* allow setting "upkeep required" anytime except the last operation was "upkeep required"
* setting the cache to expired is possible all time

This should be not high prio.

**Comment by bikerunner** [comment]
Comment from Igaze: Add a "upkeep required" record after a successful rescue for the cache.

Note: This may change the payout slightly to the "Rescue agent" but may be a bonus for the rescue.

**Comment by Thricehappy** [comment]
Also, tending should be allowed any time after an "agent" record is entered. The 24-hour block-out on tending should only be after sowing or tending a cache, not "agenting" it.

**Comment by adeadparrot** [comment]
Currently, copilot also does its own calculation for this, adding 24 hours to the 'last action' time. I suggest that the calculation be done internally (in the database) and a "no-tend" flag be set in the copilot JSON response. This will eliminate copilot doing any decision making on its own, so that if you decide to change the rules governing the no-tend flag in the future, there would be no change required for copilot code, it would simply continue to tailor its response to the notend flag, whatever rules happen to govern its existence.

**Comment by bikerunner** [comment]
We can add the flag to the copilot data provider.

**Comment by bikerunner** [comment]
Please do not merge. I found an issue if current status is "upkeep required". Reworking...
