### ISSUE TITLE
Tending and sowing uses different dates

### ISSUE THREAD

**Issue by bikerunner** [Thricehappy/EveScoutRescue#99]
There is a difference in date values set for an activity and sowing a cache. Check out "J161441" to se an example:
- tend cache as expired
- sow a new cache

Display is in reverse order afterwards. This may confuse the user afterwards.

**Comment by bikerunner** [comment]
Can you extract the activity values and cache values for the system mentioned and send it to me? There may be a time zone difference between the web server (PHP date) and the DB date.

**Comment by Thricehappy** [comment]
This issue is due to the fact that I am adjusting dates from the db to be UTC/EVE time. I can only do this on timestamps, because I need the time value to do it accurately.

Your fix tonight solved the issue for the History section, but the date for caches sown within four hours of midnight UTC (my web and db server are UTC -4) is still wrong. See, for example, https://evescoutrescue.com/esrc/search.php?system=J161441 -- dates in History section are right, but Sown On date up top is not.

This still needs to be addressed, probably by converting to UTC before entering into db in the first place. In fact, I thought there was already an issue for that.

**Comment by Thricehappy** [comment]
Yep, #82 is a related ticket. I'll leave both open for now, and we'll get this straightened out soon.

**Comment by bikerunner** [comment]
Yes, the date from the cache table should be fixed with #92 . The DB may expire caches one day before eve does if the cache is sown after downtime.

But the display issue should be fixed for now.

**Comment by Thricehappy** [comment]
I think this will be fixed going forward, now that #82 has been closed out. We can re-open if we notice any further issues.
